### PR TITLE
Added new function Get-AzureRMKeyVaultCertificatesRevival

### PR DESCRIPTION
**Pull request by Iamitzu**
This function lists deleted certificates from a specified key vault and restores a specified certificate.

### CODE REVIEW

**Comment by Iamitzu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by andyrobbins** [comment]
Thank you. Do you want to add an author credit into the function? If not, are you ok with me adding you as an author within the function later? If so, how do you want to be credited?

I may change this later to split it into two distinct functions - one to list deleted certs and one to restore a deleted cert.

**Comment by Iamitzu** [comment]
Sure, I have updated the author credit for now. Also please feel free to add the same name for further updates. Thank you!

**Comment by andyrobbins** [comment]
Thank you!

**Pull request merged**
